name: Run UI-Expanding tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run Selenide tests
        env:
          AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
          LANG: "en_GB.UTF-8"
        run: ./gradlew test --no-daemon -Dauth.username="$AUTH_USERNAME" -Dauth.password="$AUTH_PASSWORD" -Dselenide.headless=true

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
            allure_results: allure-results
            allure_history: allure-history
            keep_reports: 10

      - name: Publish report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: allure-history